exports.seed = function ( knex, Promise ) {
    return knex( "submissions" ).del()
        .then( function () {
            return Promise.all( [
                knex( "submissions" ).insert( {
                    id:1,
                    user_id: 1,
                    patient_id: 1,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "happy, I have lots of things to do today",
                    answer_5: "I dont have any",
                    read: false,
                } ),
                knex( "submissions" ).insert( {
                    id:2,
                    user_id: 1,
                    patient_id: 1,
                    survey_id: 2,
                    answer_1: "kind of, the doctor forgot to give me the sample medication, everything was moving too fast. I got my script though",
                    answer_2: "Service was great, but front desk manager seems rushed and stressed, yall need to slow down to focus on providing quality care",
                    answer_3: "Slow down a bit and dont have the TV volume set so loud in the waiting room",
                    answer_4: "maybe, there is a place closer to my house",
                    answer_5: "maybe",
                    read: false,
                } ),
                knex( "submissions" ).insert( {
                    id:3,
                    user_id: 1,
                    patient_id: 1,
                    survey_id: 3,
                    answer_1: "yes",
                    answer_2: "yes",
                    answer_3: "CVS",
                    answer_4: "yes",
                    answer_5: "yes, batteries, milk, and a birthday card",
                    read: false,
                } ),
                knex( "submissions" ).insert( {
                    id:4,
                    user_id: 1,
                    patient_id: 1,
                    survey_id: 4,
                    answer_1: "yes",
                    answer_2: "generic",
                    answer_3: "insurance covered most, but I had a copay",
                    answer_4: "no",
                    answer_5: "yes",
                    read: false,
                } ),
                knex( "submissions" ).insert( {
                    id:212,
                    user_id: 1,
                    patient_id: 1,
                    survey_id: 4,
                    answer_1: "yes",
                    answer_2: "yes",
                    answer_3: "CVS",
                    answer_4: "yes",
                    answer_5: "yes, batteries, milk, and a birthday card",
                    read: false,
                } ),
                knex( "submissions" ).insert( {
                    id:201,
                    user_id: 1,
                    patient_id: 1,
                    survey_id: 4,
                    answer_1: "yes",
                    answer_2: "generic",
                    answer_3: "insurance covered most, but I had a copay",
                    answer_4: "no",
                    answer_5: "yes",
                    read: false,
                } ),

          //test seed data for analysis page entry

                knex( "submissions" ).insert( {
                    id:10,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "Say hi to the doctor and ask a follow up question",
                    answer_2: "1 - feel great",
                    answer_3: "minor soreness in my neck",
                    answer_4: "good",
                    answer_5: "no",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:11,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "feet issue",
                    answer_2: "3 - low",
                    answer_3: "I think I have atletes food",
                    answer_4: "good, but I have itchy feet",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:12,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:13,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:14,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:15,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:16,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:17,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:18,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:19,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:20,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:21,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:22,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:23,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:24,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:25,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:26,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:27,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:28,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:29,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:30,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:31,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:32,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:33,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:34,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:35,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:36,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:37,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:38,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:39,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:40,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:41,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:42,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:43,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:44,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:45,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:46,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:47,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:48,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:49,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:50,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:51,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:52,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:53,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:54,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:55,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:56,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:57,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:58,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:59,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:60,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:61,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:62,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 1,
                    answer_1: "I have an appointment",
                    answer_2: "my butts",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),

          //test seed data for analysis page exit

                knex( "submissions" ).insert( {
                    id:63,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "Say hi to the doctor and ask a follow up question",
                    answer_2: "1 - feel great",
                    answer_3: "minor soreness in my neck",
                    answer_4: "good",
                    answer_5: "no",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:64,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "feet issue",
                    answer_2: "3 - low",
                    answer_3: "I think I have atletes food",
                    answer_4: "good, but I have itchy feet",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:65,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:66,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:67,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:68,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:69,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:70,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:71,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:72,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:73,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:74,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:75,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:76,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:77,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:78,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:79,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:80,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:81,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:82,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:83,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:84,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:85,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:86,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:87,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:88,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:89,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:90,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:91,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:92,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:93,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:94,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:95,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:96,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:97,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:98,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:99,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:100,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:101,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:102,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:103,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:104,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:105,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:106,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:107,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:108,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:109,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:110,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:111,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:112,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:113,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:114,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "2 - low",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } ),
                knex( "submissions" ).insert( {
                    id:115,
                    user_id: 1,
                    patient_id: 2,
                    survey_id: 2,
                    answer_1: "I have an appointment",
                    answer_2: "my butts",
                    answer_3: "I have a rash on my left shoulder",
                    answer_4: "none, but I need some cream",
                    answer_5: "I dont have any yet",
                    read: true,
                } )
            ] );
        } );
};
